config/routes.rb
Rails.application.routes.draw do

  root "main#index"

  get 'main/index'

  match '/signup',      to: 'users#new',            via: 'get'
  match '/signin',      to: 'sessions#new',         via: 'get'
  match '/signout',     to: 'sessions#destroy',     via: 'delete'

  match '/users/:user_id/posts/:id', to: 'posts#destroy', via: 'delete',
                                                          as: :destroy_post

  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    resources :posts
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user

  validates_presence_of :name, :content, :user_id, :picture

  before_destroy :delete_image_from_cloud

  private

  def delete_image_from_cloud
    Thread.new { a.remove_picture! }   
  end

end

app/models/post/picture_uploader.rb
class Post::PictureUploader < CarrierWave::Uploader::Base

  include Cloudinary::CarrierWave

  process :convert => 'png'
  process :tags => ['post_picture']
  
  version :standard do
    process :resize_to_fill => [100, 150, :north]
  end
  
  version :thumbnail do
    resize_to_fit(50, 50)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_secure_password

  validates_presence_of     :name
  validates_presence_of     :password, allow_blank: true
  validates_presence_of     :password_confirmation
  validates_confirmation_of :password
  
  before_create :create_remember_token
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include ApplicationHelper
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(10)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :loged_in?, except: [:show]
  before_action ->(id = params[:id]){ post_owner?(id) }, except: [:new, :create, :show]


  def new
    @post = current_user.posts.build
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Пост создан"
      redirect_to root_path
    else
      render "new"
    end
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = "Пост обновлен"
      redirect_to :back
    else
      render "edit"
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:picture, :name, :content)
  end

  def post_owner?(params_id)
    @post = Post.find_by(id: params_id)
    redirect_to root_path unless @post && owner?(@post)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :already_loged, only: [:create]

  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      sign_in @user
      redirect_to root_path
    else
      flash.now[:danger] = "Неверный пользователь или пароль"
      render "new"
    end
  end

  def destroy
    sign_out if current_user
    redirect_to root_path
  end

  private

  def already_loged
    if current_user
      flash[:danger] = "Вы уже авторизовались!"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
      flash[:success] = "Вы успешно зарегистрировались"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_container object, key
    if object.errors.include? key
      if object.errors[key].one?
        content_tag :div, object.errors[key].first, class: "alert alert-danger form-danger"
      else
        content_tag :div do
          object.errors[key].map do |error|
            concat(content_tag :div, error, class: "alert alert-danger form-danger")
          end
        end
      end
    end
  end

  def owner?(post)
    post.user_id == current_user.id
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def loged_in?
    unless current_user
      flash[:danger] = "Вы не авторизовались"
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
.row
  .col-md-12.col-lg-12
    %footer
      Минималистичный блог, 2016г

app/views/layouts/_header.html.haml
.row
  .col-md-12.col-lg-12
    .page-header
      %h1.header.text-center
        =link_to "Blog", root_path
.row
  .col-sm-12.col-lg-12
    .navbar.navbar-default.bg-success{role: "navigation"}
      .container-fluid
        - if signed_in?
          .navbar-header
            %a.navbar-brand
              Привет,
              %b #{current_user.name}!
          .collapse.navbar-collapse{data: {target:"#bs-example-navbar-collapse-1"}}
            %p.navbar-text.navbar-right
              = link_to("Выйти", signout_path, method: :delete, class: "navbar-link")
            %p.navbar-text.navbar-right
              = link_to("Создать пост", new_user_post_path(current_user), class: "navbar-link")
        - else
          .collapse.navbar-collapse{data: {target:"#bs-example-navbar-collapse-1"}}
            %p.navbar-text.navbar-right
              = link_to("Войти", signin_path, class: "navbar-link")
            %p.navbar-text.navbar-right
              = link_to("Зарегистрироваться", signup_path, class: "navbar-link")
.row
  .flash.text-center
    - flash.each do |key,value|
      %div{class: "alert alert-#{key}"} #{value}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = render partial: "layouts/header"
      .row
        .col-md-12.col-lg-12
          %main
            = yield
      = render partial: "layouts/footer"

app/views/main/index.html.haml
.articles__container
  = render @posts
%div.text-center
  = paginate @posts

app/views/posts/_post.html.haml
%article.text-justify
  %h3
    =link_to post.name, user_post_path(post.user, post)
    .article__image-container.text-center
      = cl_image_tag post.picture
  %p #{truncate(post.content, length: 600, separator: '.')}
  .article__control-panel.navbar.navbar-default
    .container-fluid
      .collapse.navbar-collapse
        %p.navbar-text
          = link_to "читать дальше", user_post_path(post.user, post), class: "read_more"
        - if signed_in? && owner?(post)
          %p.navbar-text.navbar-right
            = link_to("удалить", user_post_path(current_user, post), method: :delete)
          %p.navbar-text.navbar-right
            = link_to("редактировать", edit_user_post_path(current_user, post))

app/views/posts/edit.html.haml
.row
  = form_for [current_user, @post], html: {role: "form", class: "form-horizontal"} do |s|
    .form-group
      = s.label "Название", for: :name, class: "col-sm-offset-1 col-lg-offset-1 control-label col-md-3 col-lg-3"
      .col-md-5.col-lg-5
        = s.text_field :name, class: "form-control", id: :name, placeholder: "Название"
        = error_container @post, :name
    .form-group
      = s.label "Содержимое", for: :content, class: "col-sm-offset-1 col-lg-offset-1 control-label col-md-3 col-lg-3"
      .col-md-5.col-lg-5
        = s.text_area :content, class: "form-control", id: :content, placeholder: "Содержимое", rows: 12
        = error_container @post, :content
    .form-group
      = s.label "Изображение", for: :picture, class: "col-sm-offset-1 col-lg-offset-1 control-label col-md-3 col-lg-3"
      .col-md-5.col-lg-5
        = s.file_field :picture, class: "form-control", id: :picture, rows: 3
        = error_container @post, :picture
    .form-group
      .col-md-offset-4.col-lg-offset-4.col-md-2.col-lg-2
        = s.submit "Редактировать", class: "btn btn-primary"

app/views/posts/new.html.haml
.row
  = form_for [current_user, @post], html: {role: "form", class: "form-horizontal"} do |s|
    .form-group
      = s.label "Название", for: :name, class: "col-sm-offset-1 col-lg-offset-1 control-label col-md-3 col-lg-3"
      .col-md-5.col-lg-5
        = s.text_field :name, class: "form-control", id: :name, placeholder: "Название"
        = error_container @post, :name
    .form-group
      = s.label "Содержимое", for: :content, class: "col-sm-offset-1 col-lg-offset-1 control-label col-md-3 col-lg-3"
      .col-md-5.col-lg-5
        = s.text_area :content, class: "form-control", id: :content, placeholder: "Содержимое", rows: 3
        = error_container @post, :content
    .form-group
      = s.label "Изображение", for: :picture, class: "col-sm-offset-1 col-lg-offset-1 control-label col-md-3 col-lg-3"
      .col-md-5.col-lg-5
        = s.file_field :picture, class: "form-control", id: :picture, rows: 3
        = error_container @post, :picture
    .form-group
      .col-md-offset-4.col-lg-offset-4.col-md-2.col-lg-2
        = s.submit "Создать", class: "btn btn-primary"

app/views/posts/show.html.haml
%article.article.text-justify
  %h3
    =link_to @post.name, user_post_path(@post.user, @post)
    .article__image-container.text-center
      = cl_image_tag @post.picture
  %p #{@post.content}

app/views/users/new.html.haml
.row
  = form_for @user, html: {role: "form", class: "form-horizontal"} do |s|
    .form-group
      = s.label "Имя", for: :name, class: "col-sm-offset-1 col-lg-offset-1 control-label col-md-3 col-lg-3"
      .col-md-5.col-lg-5
        = s.text_field :name, class: "form-control", id: :name, placeholder: "Имя"
        = error_container @user, :name
    .form-group
      = s.label "Пароль", for: :password, class: "col-sm-offset-1 col-lg-offset-1 control-label col-md-3 col-lg-3"
      .col-md-5.col-lg-5
        = s.password_field :password, class: "form-control", id: :password, placeholder: "Пароль"
        = error_container @user, :password
    .form-group
      = s.label "Подтверждение пароля", for: :password_confirmation, class: "col-sm-offset-1 col-lg-offset-1 control-label col-md-3 col-lg-3"
      .col-md-9.col-lg-5
        = s.password_field :password_confirmation, class: "form-control", id: :password_confirmation, placeholder: "Подтвердите пароль"
        = error_container @user, :password_confirmation
    .form-group
      .col-md-offset-4.col-lg-offset-4.col-md-2.col-lg-2
        = s.submit "Зарегистрироваться", class: "btn btn-primary"